### PR TITLE
Event bubbling fix | closes #25

### LINKED ISSUE #25: Doesn't trigger non-change item events like a collection does.
In a collection I can fire a custom event on an item in the colleciton and it will fire on the collection, this doesn't happen on a subcollection.

```
myCollection = new MyCollection([ myModel ]);
myCollection.on('all', console.log.bind(console));

myModel.trigger('an-event', "foo") //console logs 'an-event', 'foo'

//vs...

mySubCollection = new SubCollection(myCollection);
mySubCollection.on('all', console.log.bind(console));

myModel.trigger('another-event', 'bar') //doesn't log 
```

### PR DESCRIPTION
**Pull request by aaronmccall**
<strike>Should be merged after #35.</strike> Reverted commits from #35 so that this can be merged independently.

### CODE REVIEW

**Comment by latentflip** [comment]
+1 this makes sense to me, just brings it inline with collections right? Which is what we want.

File: test/main.js [hunk 1]
```diff
@@ -577,3 +577,31 @@ test('clear filters', function (t) {
...
+    });
+
+    var customCountSub = 0;
+    sub.on('custom', function () {
+        customCountSub++;
+    });
+
+    var model = sub.at(0);
+    model.trigger('custom', model);
+
```
Comment (kamilogorek) [inline test/main.js]: I'd add `t.equal(customCountSub, 1, 'sub event triggered');` just in case :0

**Comment by kamilogorek** [comment]
Looks fine, only one small comment, but other than that +1
